Patching the amount of money we pass to Stripe
Lostmyname/solidus_gateway pull request #1
Opened 2017-02-28 10:36 UTC by alexstoick

This is because in Activemerchant we divide the number by 100 trying to
create a fraction
(https://github.com/activemerchant/active_merchant/blob/master/lib/active_merchant/billing/gateway.rb#L266-L276).

2017-02-28 16:43 UTC, chrisradford reviewed
This looks good to me, do we not need the same change on the Braintree gateway as well?

2017-02-28 16:44 UTC, jordan-brough commented on app/models/spree/gateway/stripe_gateway.rb
> +    self.currencies_without_fractions = %w(BIF BYR CLP CVE DJF GNF HUF ISK JPY KMF KRW PYG RWF UGX VND VUV XAF XOF XPF)
We can get this from the Money gem somehow can't we?

2017-02-28 16:44 UTC, alexstoick commented on app/models/spree/gateway/stripe_gateway.rb
> +    self.currencies_without_fractions = %w(BIF BYR CLP CVE DJF GNF HUF ISK JPY KMF KRW PYG RWF UGX VND VUV XAF XOF XPF)
i pulled this from `activemerchant`

2017-02-28 16:44 UTC, alexstoick commented on app/models/spree/gateway/stripe_gateway.rb
> +    self.currencies_without_fractions = %w(BIF BYR CLP CVE DJF GNF HUF ISK JPY KMF KRW PYG RWF UGX VND VUV XAF XOF XPF)
im afraid to not hardcode it and have a moving goalpost

2017-02-28 16:44 UTC, alexstoick commented
@chrisradford yes good point.

2017-02-28 16:45 UTC, jordan-brough commented on app/models/spree/gateway/stripe_gateway.rb
> +      # Example: pass 3000JPY, divide by 100, try to charge 30JPY.
Let's link to the open ActiveMerchant PR in the comments here?  The one that mentions needing a major version update for a full fix?

2017-02-28 16:45 UTC, alexstoick commented on app/models/spree/gateway/stripe_gateway.rb
> +      # Example: pass 3000JPY, divide by 100, try to charge 30JPY.
alright

2017-02-28 16:52 UTC, jordan-brough commented on app/models/spree/gateway/stripe_gateway.rb
> +        money
Does this end up working fine for currencies with `subunit_to_unit` values of 1000 and 10000?

2017-02-28 16:53 UTC, alexstoick commented on app/models/spree/gateway/stripe_gateway.rb
> +        money
since we don't use any; i'm reluctant to try to fix more than we need to.

2017-02-28 17:04 UTC, jordan-brough commented on app/models/spree/gateway/stripe_gateway.rb
> +    self.currencies_without_fractions = %w(BIF BYR CLP CVE DJF GNF HUF ISK JPY KMF KRW PYG RWF UGX VND VUV XAF XOF XPF)
how about using `provider_class.currencies_without_fractions` in `def non_fractional_currency?`?

2017-02-28 19:27 UTC, jordan-brough commented on app/models/spree/gateway/stripe_gateway.rb
> +    self.currencies_without_fractions = %w(BIF BYR CLP CVE DJF GNF HUF ISK JPY KMF KRW PYG RWF UGX VND VUV XAF XOF XPF)
we can remove the above 2 lines now right?

2017-03-01 11:03 UTC, alexstoick commented
@jordan-brough @chrisradford Updated the PR.

2017-03-01 17:31 UTC, chrisradford approved these changes
I think this makes sense, a shame it's split across two codebases but that's not something we can control

2017-03-01 18:27 UTC, jordan-brough requested changes
We're not using the Braintree patch here so wouldn't it be better to just leave that out until we get some feedback from the Solidus community?  The Braintree update needs to be in our own repo right?

2017-03-01 21:47 UTC, alexstoick commented
@jordan-brough i will check in our codebase, but i think you are right :+1:; as we do implement our own `BraintreeGateway`

2017-03-06 09:54 UTC, alexstoick commented
@jordan-brough reverted the `BraintreeGateway` changes; ready for :eyes:

2017-03-09 16:07 UTC, jordan-brough approved these changes

2017-03-09 16:29 UTC, merged